// Copyright 2023 QMK
// SPDX-License-Identifier: GPL-2.0-or-later

#include QMK_KEYBOARD_H
#include "keymap_brazilian_abnt2.h"

const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {
    [0] = LAYOUT(
		KC_UP, BR_TILD, KC_F6, KC_H, KC_F5, KC_G, KC_F4, BR_BSLS, KC_ESC, KC_LALT,
		KC_LEFT, KC_DOWN, KC_RGHT, BR_SCLN, BR_SLSH, KC_N, KC_SPC, KC_B, KC_MUTE, KC_RALT,
		KC_DOT, BR_RBRC, KC_COMM, KC_M, KC_ENT, KC_V, KC_C, KC_X, KC_Z, KC_LSFT,
		KC_L, BR_CCED, KC_K, KC_J, KC_PGDN, MO(1), KC_F, KC_D, KC_S, KC_A,
		KC_O, KC_P, KC_I, KC_U, KC_PGUP, KC_R, KC_E, KC_W, KC_Q,
		KC_END, KC_F11, KC_F12, KC_9, KC_0, KC_8, KC_7, KC_LGUI, KC_F10, KC_4, KC_3, KC_2, KC_1, KC_INS,
		KC_HOME, KC_DEL, KC_PSCR, KC_F8, KC_MINS, KC_EQL, KC_6, KC_F9, KC_5, KC_F2, KC_F1, BR_QUOT, KC_LCTL,
		KC_F7, BR_ACUT, BR_LBRC, KC_Y, KC_APP, KC_BSPC, KC_T, KC_F3, KC_CAPS, KC_TAB, KC_RSFT
    ),
    [1] = LAYOUT(
		KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, BL_DOWN, KC_TRNS, BL_UP, KC_TRNS, KC_TRNS, KC_TRNS,
		KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_MUTE, KC_TRNS,
		KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,
		KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,
		KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,
		KC_TRNS, KC_VOLD, KC_VOLU, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_MNXT, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,
		KC_TRNS, KC_TRNS, KC_TRNS, KC_MPRV, KC_TRNS, KC_TRNS, KC_TRNS, KC_MPLY, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,
		KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS)
};
